version: '3'

services:
#  db:
#    image: postgres
  web:
    build: .
    volumes:
       - web-json:/app/clientdata
    ports:
      - "80:80"
      - "443:443"
#    depends_on:
#      - db

volumes:
  web-json: